# data
data_name: mix
# clean data
clean_json_path: data/mix_sdg_clean.json
# raw data
raw_json_path: data/mix_sdg.json
# annotation dir
annotation_dir: data/annotation
vocab_path: data/sdg_vocab.json

# model
model_name: vuldnldual
embedding_mode: token+pos+type+sta
embedding_dim: 128
hidden_dim: 128
conv_layers: 3
lstm_layers: 2
pool_type: attention
kernel_type: gin

# train
cv: True
epoch: 60
batch_size: 280
num_workers: 8
lr: 0.001
milestones:
  - 20
  - 40
fine_ce_weight:
  - 0.05
  - 0.95

# save
monitor: val/n_f1

# {model_name}_{embedding_mode}_{embedding_dim}_{hidden_dim}_{conv_layers}_{lstm_layers}_{pool_type}_{fine_ce_weight[0]}
run_name: vuldnldual_token+pos+type+sta_128_128_3_2_attention_gin_0.05
